### ISSUE TITLE
Additional Query

### ISSUE THREAD

**Issue by miraydamartinez** [ed5918/Churn-Rate---CodeFlix#1]
https://github.com/ed5918/Churn-Rate---CodeFlix/blob/a3628e5f1a792d546c167784b8ef68d32c4d2edd/code.sql#L24-L26

After the parenthesis on line 24, you could just add a comma and a table would automatically update. There is no need to select * from subscriptions again. I wasn't sure if this was intentional or not, but just a note for future reference!

**Comment by ed5918** [comment]
Hi Mirayda, 
Thank you for your time to review my code. This seems to be typo, but thanks for the comment. I should be more patient and review my code before i submitted it.
