### ISSUE TITLE
END AS not END

### ISSUE THREAD

**Issue by miraydamartinez** [ed5918/Churn-Rate---CodeFlix#2]
https://github.com/ed5918/Churn-Rate---CodeFlix/blob/a3628e5f1a792d546c167784b8ef68d32c4d2edd/code.sql#L76

If you want to end the case, you can just write END, but since you wrote is_active_82, I'm assuming you wanted to END AS instead. It's important to always look at your code to ensure it does what you want it to. Also, you say is_active_82, did you mean to assign this earlier in your code? (WHEN segment = 82)?

**Comment by ed5918** [comment]
Thanks. This error is from my rush. I've to be more careful and patient .
Thanks
