### ISSUE TITLE
Repeated Code

### ISSUE THREAD

**Issue by miraydamartinez** [ed5918/Churn-Rate---CodeFlix#4]
https://github.com/ed5918/Churn-Rate---CodeFlix/blob/a3628e5f1a792d546c167784b8ef68d32c4d2edd/code.sql#L267-L342

These lines continue to be repeated throughout the project. Is there a significance to having them there more than once? If not, you don't need to copy and paste your past queries with your new ones. It makes code difficult to read and takes away from the neatness of your project. After doing one query, it should stay there.

**Comment by ed5918** [comment]
I was not sure if i have to add the whole code once or for each questions.
Thanks for the comment
